# SPDX-FileCopyrightText: 2025 Hana Kretzer <hanakretzer@gmail.com>
#
# SPDX-License-Identifier: MIT

[drop2beets]
fetch.git = "https://github.com/martinkirch/drop2beets.git"
src.git = "https://github.com/martinkirch/drop2beets.git"

[lidarr]
fetch.url = "https://lidarr.servarr.com/v1/update/develop/updatefile?version=$ver&os=linux&runtime=netcore&arch=x64"
src.cmd = "curl -L 'https://lidarr.servarr.com/v1/update/develop/changes' --fail | jq -r '.[0].version'"
url.name = "lidarr-src-$ver.tar.gz"

[luarenamer]
fetch.git = "https://github.com/Mik1ll/LuaRenamer.git"
src.github_tag = "Mik1ll/LuaRenamer"

[midnight-theme]
fetch.git = "https://github.com/refact0r/midnight-discord.git"
src.git = "https://github.com/refact0r/midnight-discord.git"

[openrgb]
pinned = true
fetch.git = "https://gitlab.com/CalcProgrammer1/OpenRGB.git"
src.git = "https://gitlab.com/CalcProgrammer1/OpenRGB.git"

[osu-lazer-bin]
fetch.url = "https://github.com/ppy/osu/releases/download/$ver/osu.AppImage"
src.github_tag = "ppy/osu"
src.include_regex = "202\\d\\.\\d{1,4}\\.\\d"

[prowlarr]
fetch.git = "https://github.com/Prowlarr/Prowlarr.git"
src.github_tag = "Prowlarr/Prowlarr"

[pyon]
fetch.git = "https://github.com/nanoyaki/pyon.git"
src.git = "https://github.com/nanoyaki/pyon.git"

[python-modernize]
fetch.git = "https://github.com/PyCQA/modernize.git"
src.git = "https://github.com/PyCQA/modernize.git"

[rofi-themes]
fetch.git = "https://github.com/adi1090x/rofi.git"
src.git = "https://github.com/adi1090x/rofi.git"

[shoko]
fetch.tarball = "https://github.com/ShokoAnime/ShokoServer/archive/refs/tags/v$ver.tar.gz"
src.github_tag = "ShokoAnime/ShokoServer"
src.include_regex = '.*-dev\..*'
src.prefix = "v"

[shoko-webui]
fetch.tarball = "https://github.com/ShokoAnime/Shoko-WebUI/archive/refs/tags/v$ver.tar.gz"
src.github_tag = "ShokoAnime/Shoko-WebUI"
src.include_regex = '.*-dev\..*'
src.prefix = "v"

[shokofin]
fetch.tarball = "https://github.com/ShokoAnime/Shokofin/archive/refs/tags/v$ver.tar.gz"
src.github_tag = "ShokoAnime/Shokofin"
src.include_regex = '.*-dev\..*'
src.prefix = "v"

[suwayomi-server]
fetch.git = "https://github.com/Suwayomi/Suwayomi-Server.git"
src.git = "https://github.com/Suwayomi/Suwayomi-Server.git"

[suwayomi-webui]
fetch.git = "https://github.com/Suwayomi/Suwayomi-WebUI.git"
src.git = "https://github.com/Suwayomi/Suwayomi-WebUI.git"

[whisparr]
fetch.url = "https://whisparr.servarr.com/v1/update/eros/updatefile?version=$ver&os=linux&runtime=netcore&arch=x64"
src.cmd = "curl -L 'https://whisparr.servarr.com/v1/update/eros/changes' --fail | jq -r '.[0].version'"
url.name = "whisparr-src-$ver.tar.gz"
