# SPDX-FileCopyrightText: 2025 Hana Kretzer <hanakretzer@gmail.com>
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "nanopkgs"
SPDX-PackageSupplier = "Hana Kretzer <hanakretzer@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/nanoyaki/nanopkgs"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["_sources/**", "_versions/*", ".envrc", ".gitignore", "**/*.patch", "**/deps.json"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Hana Kretzer <hanakretzer@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
