# SPDX-FileCopyrightText: 2025 Hana Kretzer <hanakretzer@gmail.com>
#
# SPDX-License-Identifier: MIT
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flake checks
        run: nix flake check
