# SPDX-FileCopyrightText: 2025 Hana Kretzer <hanakretzer@gmail.com>
#
# SPDX-License-Identifier: MIT
on:
  push:
    paths:
      - '**/*.nix'
      - flake.lock
    branches:
      - main
  pull_request:

jobs:
  checks:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flake checks
        run: nix --extra-experimental-features pipe-operators flake check
