# SPDX-FileCopyrightText: 2025 Hana Kretzer <hanakretzer@gmail.com>
#
# SPDX-License-Identifier: MIT
on:
  push:
    paths:
      - '**/*.nix'
      - flake.lock
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NIX_CONFIG: |
    extra-experimental-features = pipe-operators

jobs:
  eval:
    runs-on: native
    outputs:
      to-check: ${{ steps.eval.outputs.to-check }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Eval checks
        id: eval
        run: |
          nix-eval-jobs \
            --option eval-cache false \
            --workers 32 \
            --max-memory-size 4096 \
            --option accept-flake-config true \
            --force-recurse \
            --check-cache-status \
            --show-trace \
            --flake '.#checks.x86_64-linux' \
            > evaled

          echo "to-check=$(
            jq -s -r -c \
            'map({ name: .name, path: (select(.isCached == false) | .drvPath), attr: ([.system] + .attrPath | join (".")) })' \
            ./evaled
          )" > $FORGEJO_OUTPUT

  check:
    name: Check ${{ matrix.checks.name }}
    runs-on: native
    needs: eval
    strategy:
      matrix:
        checks: ${{ fromJSON(needs.eval.outputs.to-check) }}
    steps:
      - name: Check outputs
        id: check
        run: |-
          nix build \
            -L \
            --show-trace \
            --keep-going \
            --max-silent-time 1200 \
            --out-link "result-${{ matrix.checks.attr }}" \
            "${{ matrix.checks.path }}"'^*'

      - name: Upload to cache
        env:
          CACHE_TOKEN: ${{ secrets.CACHE_TOKEN }}
        run: |-
          attic login thelessone https://binarycache.theless.one "$CACHE_TOKEN"
          attic push global "${{ matrix.checks.path }}"

