# SPDX-FileCopyrightText: 2025 Hana Kretzer <hanakretzer@gmail.com>
#
# SPDX-License-Identifier: MIT
on:
  push:
    paths:
      - '**/*.nix'
      - flake.lock
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NIX_CONFIG: |
    extra-experimental-features = pipe-operators

jobs:
  checks:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Eval checks
        id: eval
        run: |
          nix-eval-jobs \
            --option eval-cache false \
            --workers 32 \
            --max-memory-size 4096 \
            --option accept-flake-config true \
            --force-recurse \
            --check-cache-status \
            --show-trace \
            --flake '.#checks.x86_64-linux' \
            > evaled

      - name: Check changed
        run: |-
          set -eo pipefail

          for check in $(
            jq -s -r -c \
            'map({ path: (select(.isCached == false) | .drvPath), attr: ([.system] + .attrPath | join (".")) })[]' \
            ./evaled
          ); do
            nix build \
              -L \
              --show-trace \
              --keep-going \
              --max-silent-time 1200 \
              --out-link "result-$(jq -r '.attr' <<< $check)" \
              "$(jq -r '.path' <<< $check)^*"
          done
