# SPDX-FileCopyrightText: 2025 Hana Kretzer <hanakretzer@gmail.com>
#
# SPDX-License-Identifier: MIT
on:
  schedule:
    - cron: '0 1 * * *' # 3 AM CEST
  workflow_dispatch:

# Not implemented yet, keep for the future
permissions:
  pull-requests: write

env:
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    access-tokens = github.com=${{ secrets.HUBGIT_TOKEN }}

jobs:
  update:
    runs-on: nix
    if: forge.event_name != 'workflow_dispatch' || forge.ref == 'refs/heads/main'
    steps:
      - name: Install dependencies
        run: >
          nix profile install
          nixpkgs#nodejs nixpkgs#tea

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure git
        uses: https://git.theless.one/actions/configure-git@v1
        with:
          username: forgejo-bot
          email: git@theless.one

      - name: Update packages
        env:
          LANG: C.UTF-8
        run: |
          git checkout -B chore/auto-update refs/heads/main
          nix run .#update

      - name: Update readme
        run: |
          nix run .#update-readme
          git add README.md
          git commit --amend --no-edit
          git push -u origin chore/auto-update -f

      - name: Create Forgejo Pull Request
        uses: https://git.theless.one/actions/create-pr@v3
        with:
          source-branch: chore/auto-update
          title: 'chore: update packages'
          description: >
            Automated pull request to update the maintaned packages
          token: ${{ secrets.FORGEJO_BOT_TOKEN }}
          auto-merge: 'true'
