# SPDX-FileCopyrightText: 2025 Hana Kretzer <hanakretzer@gmail.com>
#
# SPDX-License-Identifier: MIT
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  check-branch:
    runs-on: native
    steps:
      - name: Check branch
        if: forge.event_name == 'workflow_dispatch' && forge.ref != 'refs/heads/main'
        run: exit 1

  update:
    runs-on: native
    needs: check-branch
    steps:
      - name: Checkout repo
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Setup git
        run: |
          git config --local user.name "forgejo-actions[bot]"
          git config --local user.email "hanakretzer+forgejo-actions@gmail.com"
          git checkout -b chore/auto-update

      - name: Setup keys
        env:
          HUBGIT_TOKEN: ${{ secrets.HUBGIT_TOKEN }}
        run: |
          echo \
            "[keys]
            github = \"$HUBGIT_TOKEN\"
            " > keys.toml
          chmod 400 ./keys.toml

      - name: Update packages
        env:
          LANG: C.UTF-8
        run: nix run .#update -- ./keys.toml

      - name: Update readme
        run: |
          nix run .#update-readme
          git add README.md
          git commit --amend --no-edit

      - name: Create Forgejo Pull Request
        id: create-pr
        env:
          FORGEJO_LOGIN: forgejo-actions
        run: |
          tea login delete "$FORGEJO_LOGIN" || true
          tea login add --name "$FORGEJO_LOGIN" --url "$FORGEJO_SERVER_URL" --token "$FORGEJO_TOKEN" || true

          git push -u origin chore/auto-update
          PR_NUMBER="$(
            tea pr create \
              -l "$FORGEJO_LOGIN" \
              -t 'chore: update locks' \
              -d 'Automated pull request to update locks for maintained programs' \
              -r "$FORGEJO_REPOSITORY" \
              | tail \
              | grep -oP '/\K\d+'
          )"

          echo "pr=${PR_NUMBER}" >> $FORGEJO_OUTPUT

      - name: Enable Auto-Merge
        env:
          PR_NUMBER: ${{ steps.create-pr.outputs.pr }}
        run: >-
          curl -X POST
            -H "Authorization: token $FORGEJO_TOKEN"
            -H "Content-Type: application/json"
            -d '{
              "Do": "auto",
              "merge_when_checks_succeed": true
            }'
            "${FORGEJO_SERVER_URL}/api/v1/repos/${FORGEJO_REPOSITORY}/pulls/${PR_NUMBER}/automerge"
