# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  beet = {
    pname = "beet";
    version = "v0.111.0";
    src = fetchgit {
      url = "https://github.com/mcbeet/beet.git";
      rev = "v0.111.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cZG5HKHVAUh+oTb+ULPBWyqXrdgvTTbYTyqewYGcxWQ=";
    };
  };
  bolt = {
    pname = "bolt";
    version = "v0.49.2";
    src = fetchgit {
      url = "https://github.com/mcbeet/bolt.git";
      rev = "v0.49.2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-kJgZVwMZ1Z50KSYFA16SF3zMpGgYbX3ryFgYTso+JUM=";
    };
  };
  drop2beets = {
    pname = "drop2beets";
    version = "6bda199a8f5710b2265ce66cff8f2d3c6f09f6dc";
    src = fetchgit {
      url = "https://github.com/martinkirch/drop2beets.git";
      rev = "6bda199a8f5710b2265ce66cff8f2d3c6f09f6dc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YvtdAjRbEh9tb60gp6Lh70QSISPn6uZNWi09EF0Dkwg=";
    };
    date = "2024-04-21";
  };
  fireshare = {
    pname = "fireshare";
    version = "v1.2.27";
    src = fetchgit {
      url = "https://github.com/ShaneIsrael/fireshare.git";
      rev = "v1.2.27";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+4IR/lsfiyrY0wwsp8/yu2DpawS9pkbqUyIwE6AP39o=";
    };
  };
  flaresolverr = {
    pname = "flaresolverr";
    version = "v3.3.25";
    src = fetchgit {
      url = "https://github.com/FlareSolverr/FlareSolverr.git";
      rev = "v3.3.25";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AGRqJOIIePaJH0j0eyMFJ6Kddul3yXF6uw6dPMnskmY=";
    };
  };
  jmc = {
    pname = "jmc";
    version = "v1.2.19-alpha.1";
    src = fetchgit {
      url = "https://github.com/WingedSeal/jmc.git";
      rev = "v1.2.19-alpha.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-zGGNYxAsO9uHrFuh8VnLnnLFJ5UPxcBOP8pU/yDYs/g=";
    };
  };
  lidarr = {
    pname = "lidarr";
    version = "2.13.2.4685";
    src = fetchurl {
      url = "https://lidarr.servarr.com/v1/update/develop/updatefile?version=2.13.2.4685&os=linux&runtime=netcore&arch=x64";
      name = "lidarr-src-2.13.2.4685.tar.gz";
      sha256 = "sha256-VzTypCJ0VE40cWj3gLAj7Z0qO/bbvc/stAUrjgY8l3o=";
    };
  };
  luarenamer = {
    pname = "luarenamer";
    version = "v5.9.0";
    src = fetchgit {
      url = "https://github.com/Mik1ll/LuaRenamer.git";
      rev = "v5.9.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aFhgPmacMyfOChCKQr3CUtbjvPP7II816DWYk3Uk6NE=";
    };
  };
  mecha = {
    pname = "mecha";
    version = "v0.99.0";
    src = fetchgit {
      url = "https://github.com/mcbeet/mecha.git";
      rev = "v0.99.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DbpLkKzva+PmHig50qjmuS7v3uk1e8i9a0IF/qPHkh4=";
    };
  };
  midnight-theme = {
    pname = "midnight-theme";
    version = "9287e825c03f15379d26dfb00039c19d5c4de210";
    src = fetchgit {
      url = "https://github.com/refact0r/midnight-discord.git";
      rev = "9287e825c03f15379d26dfb00039c19d5c4de210";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-we2wY5n2zvlpeuq2o2JVyj39+pDLj6Iv/Bm81OtuvDU=";
    };
    date = "2025-07-31";
  };
  openrgb = {
    pname = "openrgb";
    version = "f76dbb08cc84f786338057fc43f5c4163e593992";
    src = fetchgit {
      url = "https://gitlab.com/CalcProgrammer1/OpenRGB.git";
      rev = "f76dbb08cc84f786338057fc43f5c4163e593992";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ukuGCX+SBf0gMDxb0AM+ePShkm+6JOJ2eZQHJqHHlgs=";
    };
    date = "2025-07-07";
  };
  osu-lazer-bin = {
    pname = "osu-lazer-bin";
    version = "2025.607.1";
    src = fetchurl {
      url = "https://github.com/ppy/osu/releases/download/2025.607.1/osu.AppImage";
      sha256 = "sha256-xLniL2fogWFAaEADvX2YL7lRGHGew7kc3Ni1fhPzs1c=";
    };
  };
  prowlarr = {
    pname = "prowlarr";
    version = "v2.0.5.5160";
    src = fetchgit {
      url = "https://github.com/Prowlarr/Prowlarr.git";
      rev = "v2.0.5.5160";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xSAEDcBaItA+retaSKtEI6wlwj5Knfi4RwUN6GGYms0=";
    };
  };
  pyon = {
    pname = "pyon";
    version = "06a076e7be314813ff71d823f200e6c3e0b2d232";
    src = fetchgit {
      url = "https://github.com/nanoyaki/pyon.git";
      rev = "06a076e7be314813ff71d823f200e6c3e0b2d232";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-SgMYeWSQP3hk6t5jBHP2lIPe3ig7PFEhY2KnIHKM76s=";
    };
    date = "2025-03-22";
  };
  python-modernize = {
    pname = "python-modernize";
    version = "f06b20ad4728267ebcacb96075118529541697cd";
    src = fetchgit {
      url = "https://github.com/PyCQA/modernize.git";
      rev = "f06b20ad4728267ebcacb96075118529541697cd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5GKIo3FjgM+8Ntf7OiBkR/JVvBq5+LFPtytmN5g4wwc=";
    };
    date = "2021-01-11";
  };
  rofi-themes = {
    pname = "rofi-themes";
    version = "093c1a79f58daab358199c4246de50357e5bf462";
    src = fetchgit {
      url = "https://github.com/adi1090x/rofi.git";
      rev = "093c1a79f58daab358199c4246de50357e5bf462";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-iUX0Quae06tGd7gDgXZo1B3KYgPHU+ADPBrowHlv02A=";
    };
    date = "2025-07-26";
  };
  shoko = {
    pname = "shoko";
    version = "5.1.0-dev.123";
    src = fetchTarball {
      url = "https://github.com/ShokoAnime/ShokoServer/archive/refs/tags/v5.1.0-dev.123.tar.gz";
      sha256 = "sha256-HEHNreazsJ38W7DSZ4Bl0k+RueprExDMfqqMsvoREYo=";
    };
  };
  shoko-webui = {
    pname = "shoko-webui";
    version = "2.3.0-dev.7";
    src = fetchTarball {
      url = "https://github.com/ShokoAnime/Shoko-WebUI/archive/refs/tags/v2.3.0-dev.7.tar.gz";
      sha256 = "sha256-j6Q+YjhQEgAuNW0FxIM2k7OAFsZLI0UtKD9wqq2eZbc=";
    };
  };
  shokofin = {
    pname = "shokofin";
    version = "5.0.4-dev.30";
    src = fetchTarball {
      url = "https://github.com/ShokoAnime/Shokofin/archive/refs/tags/v5.0.4-dev.30.tar.gz";
      sha256 = "sha256-iik4dVpozPFE4unOm07liS7sfOH5+ITHVQRVtMjy5P4=";
    };
  };
  stash-scrapers = {
    pname = "stash-scrapers";
    version = "970fdb79f760297002f12116ad5dd39d5b8eac2c";
    src = fetchgit {
      url = "https://github.com/stashapp/CommunityScrapers.git";
      rev = "970fdb79f760297002f12116ad5dd39d5b8eac2c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-MSntL9lFFKn1nMSy06KCi49HD2POSRFpqwuATD54+Pk=";
    };
    date = "2025-08-24";
  };
  suwayomi-server = {
    pname = "suwayomi-server";
    version = "46e2ef125a6b5c02a5fed314e99aaebee73b5633";
    src = fetchgit {
      url = "https://github.com/Suwayomi/Suwayomi-Server.git";
      rev = "46e2ef125a6b5c02a5fed314e99aaebee73b5633";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-io5IozNNogCseh5D7ZSl3XwEY4dGFdkMg50c9mgPEy4=";
    };
    date = "2025-08-24";
  };
  suwayomi-webui = {
    pname = "suwayomi-webui";
    version = "0f8c6496f89f8a1a912757ea7a483254577e4c82";
    src = fetchgit {
      url = "https://github.com/Suwayomi/Suwayomi-WebUI.git";
      rev = "0f8c6496f89f8a1a912757ea7a483254577e4c82";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/6IymUnJN5hYTc53GHs07FhkAcjAjHJgG57LaeeAIZA=";
    };
    date = "2025-08-24";
  };
  tokenstream = {
    pname = "tokenstream";
    version = "v1.7.0";
    src = fetchgit {
      url = "https://github.com/vberlier/tokenstream.git";
      rev = "v1.7.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-idTgTVaZkF6M9ly5HzqmHtUUc7Bp5VrR2EioDSHmThM=";
    };
  };
  whisparr = {
    pname = "whisparr";
    version = "3.0.0.1247";
    src = fetchurl {
      url = "https://whisparr.servarr.com/v1/update/eros/updatefile?version=3.0.0.1247&os=linux&runtime=netcore&arch=x64";
      name = "whisparr-src-3.0.0.1247.tar.gz";
      sha256 = "sha256-ZA5lCIwIlNjbm2NrwIVBnxSmgGE34WDPbSOAgu0Q/nI=";
    };
  };
}
