# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  beet = {
    pname = "beet";
    version = "v0.111.0";
    src = fetchgit {
      url = "https://github.com/mcbeet/beet.git";
      rev = "v0.111.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cZG5HKHVAUh+oTb+ULPBWyqXrdgvTTbYTyqewYGcxWQ=";
    };
  };
  bolt = {
    pname = "bolt";
    version = "v0.49.2";
    src = fetchgit {
      url = "https://github.com/mcbeet/bolt.git";
      rev = "v0.49.2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-kJgZVwMZ1Z50KSYFA16SF3zMpGgYbX3ryFgYTso+JUM=";
    };
  };
  drop2beets = {
    pname = "drop2beets";
    version = "6bda199a8f5710b2265ce66cff8f2d3c6f09f6dc";
    src = fetchgit {
      url = "https://github.com/martinkirch/drop2beets.git";
      rev = "6bda199a8f5710b2265ce66cff8f2d3c6f09f6dc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YvtdAjRbEh9tb60gp6Lh70QSISPn6uZNWi09EF0Dkwg=";
    };
    date = "2024-04-21";
  };
  fireshare = {
    pname = "fireshare";
    version = "v1.2.30";
    src = fetchgit {
      url = "https://github.com/ShaneIsrael/fireshare.git";
      rev = "v1.2.30";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5ox3I4qPldfGpgf3G/uOunK05l11xAmKoW6Qk0fdSrA=";
    };
  };
  flaresolverr = {
    pname = "flaresolverr";
    version = "v3.4.1";
    src = fetchgit {
      url = "https://github.com/FlareSolverr/FlareSolverr.git";
      rev = "v3.4.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ySYH4Ty6Z1mZWPIhIIX0+78RiozEHJ++3C4kBj7MfU0=";
    };
  };
  ftb-server-installer = {
    pname = "ftb-server-installer";
    version = "v1.0.29";
    src = fetchgit {
      url = "https://github.com/FTBTeam/FTB-Server-Installer.git";
      rev = "v1.0.29";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-FT/7Gzu34XYUF9kMb/dafJ5nmcFihGu10MEbAQ/UNpw=";
    };
  };
  jmc = {
    pname = "jmc";
    version = "v1.2.19-alpha.1";
    src = fetchgit {
      url = "https://github.com/WingedSeal/jmc.git";
      rev = "v1.2.19-alpha.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-zGGNYxAsO9uHrFuh8VnLnnLFJ5UPxcBOP8pU/yDYs/g=";
    };
  };
  lidarr = {
    pname = "lidarr";
    version = "2.14.3.4791";
    src = fetchurl {
      url = "https://lidarr.servarr.com/v1/update/develop/updatefile?version=2.14.3.4791&os=linux&runtime=netcore&arch=x64";
      name = "lidarr-src-2.14.3.4791.tar.gz";
      sha256 = "sha256-A7khU6ayTyX7JkeOHsojEmtfqIfWn+c+UxTagyS3J1A=";
    };
  };
  luarenamer = {
    pname = "luarenamer";
    version = "v5.9.0";
    src = fetchgit {
      url = "https://github.com/Mik1ll/LuaRenamer.git";
      rev = "v5.9.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aFhgPmacMyfOChCKQr3CUtbjvPP7II816DWYk3Uk6NE=";
    };
  };
  mc-modpack-downloader = {
    pname = "mc-modpack-downloader";
    version = "81c580e887a079ba62be12a7adf58b5ef4809f4a";
    src = fetchgit {
      url = "https://github.com/newo-2001/MC-Modpack-Downloader.git";
      rev = "81c580e887a079ba62be12a7adf58b5ef4809f4a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hU7/cSfMc7kcmgPELJFUrY3t9IVQ/bL0mSzt2fwA2Pg=";
    };
    date = "2025-03-28";
  };
  mecha = {
    pname = "mecha";
    version = "v0.99.0";
    src = fetchgit {
      url = "https://github.com/mcbeet/mecha.git";
      rev = "v0.99.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DbpLkKzva+PmHig50qjmuS7v3uk1e8i9a0IF/qPHkh4=";
    };
  };
  midnight-theme = {
    pname = "midnight-theme";
    version = "694f0e8600d490d6dc3a98aa2fae6322f473490d";
    src = fetchgit {
      url = "https://github.com/refact0r/midnight-discord.git";
      rev = "694f0e8600d490d6dc3a98aa2fae6322f473490d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TuuIOOcCAjhgm+DE58UY9KNh0F9h4LpN82DZziuhVyg=";
    };
    date = "2025-09-30";
  };
  openrgb = {
    pname = "openrgb";
    version = "f76dbb08cc84f786338057fc43f5c4163e593992";
    src = fetchgit {
      url = "https://gitlab.com/CalcProgrammer1/OpenRGB.git";
      rev = "f76dbb08cc84f786338057fc43f5c4163e593992";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ukuGCX+SBf0gMDxb0AM+ePShkm+6JOJ2eZQHJqHHlgs=";
    };
    date = "2025-07-07";
  };
  osu-lazer-bin = {
    pname = "osu-lazer-bin";
    version = "2025.912.0-lazer";
    src = fetchurl {
      url = "https://github.com/ppy/osu/releases/download/2025.912.0-lazer/osu.AppImage";
      sha256 = "sha256-73UY3RJp0pFfbxRWX8qSnLeoZB/BRGtucmQClJP7Qwg=";
    };
  };
  prowlarr = {
    pname = "prowlarr";
    version = "v2.1.2.5186";
    src = fetchgit {
      url = "https://github.com/Prowlarr/Prowlarr.git";
      rev = "v2.1.2.5186";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-VZQFU/sB45HajrC9ITUd9lA5Le0nB66otLkz1NU7nYk=";
    };
  };
  pyon = {
    pname = "pyon";
    version = "06a076e7be314813ff71d823f200e6c3e0b2d232";
    src = fetchgit {
      url = "https://github.com/nanoyaki/pyon.git";
      rev = "06a076e7be314813ff71d823f200e6c3e0b2d232";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-SgMYeWSQP3hk6t5jBHP2lIPe3ig7PFEhY2KnIHKM76s=";
    };
    date = "2025-03-22";
  };
  python-modernize = {
    pname = "python-modernize";
    version = "f06b20ad4728267ebcacb96075118529541697cd";
    src = fetchgit {
      url = "https://github.com/PyCQA/modernize.git";
      rev = "f06b20ad4728267ebcacb96075118529541697cd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5GKIo3FjgM+8Ntf7OiBkR/JVvBq5+LFPtytmN5g4wwc=";
    };
    date = "2021-01-11";
  };
  rofi-themes = {
    pname = "rofi-themes";
    version = "093c1a79f58daab358199c4246de50357e5bf462";
    src = fetchgit {
      url = "https://github.com/adi1090x/rofi.git";
      rev = "093c1a79f58daab358199c4246de50357e5bf462";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-iUX0Quae06tGd7gDgXZo1B3KYgPHU+ADPBrowHlv02A=";
    };
    date = "2025-07-26";
  };
  shoko = {
    pname = "shoko";
    version = "5.1.0-dev.128";
    src = fetchTarball {
      url = "https://github.com/ShokoAnime/ShokoServer/archive/refs/tags/v5.1.0-dev.128.tar.gz";
      sha256 = "sha256-C+QXWXopY9tFid290IoXrGTwEJDLQ4ZJXDP/p33bvnw=";
    };
  };
  shoko-webui = {
    pname = "shoko-webui";
    version = "2.3.0-dev.14";
    src = fetchTarball {
      url = "https://github.com/ShokoAnime/Shoko-WebUI/archive/refs/tags/v2.3.0-dev.14.tar.gz";
      sha256 = "sha256-gYYZJ/dHO3pv+c4fURWkCYEq7jKlKUb64PsVQzXkm5Y=";
    };
  };
  shokofin = {
    pname = "shokofin";
    version = "5.0.4-dev.42";
    src = fetchTarball {
      url = "https://github.com/ShokoAnime/Shokofin/archive/refs/tags/v5.0.4-dev.42.tar.gz";
      sha256 = "sha256-edG8Alr2fTafS+DQce3rAyoC1NzW+A+Y9MCD5dG87nI=";
    };
  };
  stash-scrapers = {
    pname = "stash-scrapers";
    version = "98d702e1c61a7b766a04e5575e2f4c5dbc2da21b";
    src = fetchgit {
      url = "https://github.com/stashapp/CommunityScrapers.git";
      rev = "98d702e1c61a7b766a04e5575e2f4c5dbc2da21b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-smDj4pPZCogUfNG4V+1Jnct/BjpOLsV/yk9efDGk+Mc=";
    };
    date = "2025-09-29";
  };
  suwayomi-server = {
    pname = "suwayomi-server";
    version = "2e0f72f1820f2337ed8542314f6e6b78f8fa064a";
    src = fetchgit {
      url = "https://github.com/Suwayomi/Suwayomi-Server.git";
      rev = "2e0f72f1820f2337ed8542314f6e6b78f8fa064a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4QGZXbjadlDF+NBfR5nFQZaZ1fEtFDdeNlQIK/mTReU=";
    };
    date = "2025-09-29";
  };
  suwayomi-webui = {
    pname = "suwayomi-webui";
    version = "c1f9699834c3a85456047c73bc442884b6936961";
    src = fetchgit {
      url = "https://github.com/Suwayomi/Suwayomi-WebUI.git";
      rev = "c1f9699834c3a85456047c73bc442884b6936961";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-WMKqXtT9P1Dsmwf8ad6o+W85N36gEwxzDma4Yxv+iQ8=";
    };
    date = "2025-09-28";
  };
  tokenstream = {
    pname = "tokenstream";
    version = "v1.7.0";
    src = fetchgit {
      url = "https://github.com/vberlier/tokenstream.git";
      rev = "v1.7.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-idTgTVaZkF6M9ly5HzqmHtUUc7Bp5VrR2EioDSHmThM=";
    };
  };
  whisparr = {
    pname = "whisparr";
    version = "3.0.1.1304";
    src = fetchurl {
      url = "https://whisparr.servarr.com/v1/update/eros/updatefile?version=3.0.1.1304&os=linux&runtime=netcore&arch=x64";
      name = "whisparr-src-3.0.1.1304.tar.gz";
      sha256 = "sha256-B0lJb6e8rIYwWu24NxcvaxBiynQuB3ZK9Bh2VmaHZLc=";
    };
  };
}
