# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  drop2beets = {
    pname = "drop2beets";
    version = "6bda199a8f5710b2265ce66cff8f2d3c6f09f6dc";
    src = fetchgit {
      url = "https://github.com/martinkirch/drop2beets.git";
      rev = "6bda199a8f5710b2265ce66cff8f2d3c6f09f6dc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YvtdAjRbEh9tb60gp6Lh70QSISPn6uZNWi09EF0Dkwg=";
    };
    date = "2024-04-21";
  };
  lidarr = {
    pname = "lidarr";
    version = "2.13.0.4664";
    src = fetchurl {
      url = "https://lidarr.servarr.com/v1/update/develop/updatefile?version=2.13.0.4664&os=linux&runtime=netcore&arch=x64";
      name = "lidarr-src-2.13.0.4664.tar.gz";
      sha256 = "sha256-ODIPtlpzZcZWZxTBXt5r5xpJ4ZWbpGnJ2Na7QVEvrlw=";
    };
  };
  luarenamer = {
    pname = "luarenamer";
    version = "v5.6.0";
    src = fetchgit {
      url = "https://github.com/Mik1ll/LuaRenamer.git";
      rev = "v5.6.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Ljbu/3Cdv2zhX0/6+dmIhh78W5JfDl322PqvWsH57fc=";
    };
  };
  midnight-theme = {
    pname = "midnight-theme";
    version = "0a080c1b62898a8776c1cb117989b02660e32ac7";
    src = fetchgit {
      url = "https://github.com/refact0r/midnight-discord.git";
      rev = "0a080c1b62898a8776c1cb117989b02660e32ac7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ZxC8XfIIPhszo+BouVLSA6Tq0PB4M0nTkmmScTyVA7M=";
    };
    date = "2025-06-30";
  };
  openrgb = {
    pname = "openrgb";
    version = "f76dbb08cc84f786338057fc43f5c4163e593992";
    src = fetchgit {
      url = "https://gitlab.com/CalcProgrammer1/OpenRGB.git";
      rev = "f76dbb08cc84f786338057fc43f5c4163e593992";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ukuGCX+SBf0gMDxb0AM+ePShkm+6JOJ2eZQHJqHHlgs=";
    };
    date = "2025-07-07";
  };
  osu-lazer-bin = {
    pname = "osu-lazer-bin";
    version = "2025.607.1";
    src = fetchurl {
      url = "https://github.com/ppy/osu/releases/download/2025.607.1/osu.AppImage";
      sha256 = "sha256-xLniL2fogWFAaEADvX2YL7lRGHGew7kc3Ni1fhPzs1c=";
    };
  };
  prowlarr = {
    pname = "prowlarr";
    version = "v2.0.1.5101";
    src = fetchgit {
      url = "https://github.com/Prowlarr/Prowlarr.git";
      rev = "v2.0.1.5101";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YPDBrhehXH4mBiGODBa72khGzpxVkjEtc9VLl9y90o0=";
    };
  };
  pyon = {
    pname = "pyon";
    version = "06a076e7be314813ff71d823f200e6c3e0b2d232";
    src = fetchgit {
      url = "https://github.com/nanoyaki/pyon.git";
      rev = "06a076e7be314813ff71d823f200e6c3e0b2d232";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-SgMYeWSQP3hk6t5jBHP2lIPe3ig7PFEhY2KnIHKM76s=";
    };
    date = "2025-03-22";
  };
  python-modernize = {
    pname = "python-modernize";
    version = "f06b20ad4728267ebcacb96075118529541697cd";
    src = fetchgit {
      url = "https://github.com/PyCQA/modernize.git";
      rev = "f06b20ad4728267ebcacb96075118529541697cd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5GKIo3FjgM+8Ntf7OiBkR/JVvBq5+LFPtytmN5g4wwc=";
    };
    date = "2021-01-11";
  };
  rofi-themes = {
    pname = "rofi-themes";
    version = "d6ae47205a375108f7fc7c96b6dc9d647951dcad";
    src = fetchgit {
      url = "https://github.com/adi1090x/rofi.git";
      rev = "d6ae47205a375108f7fc7c96b6dc9d647951dcad";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XJP7lKSataPkQayVzUElrUnOBJhhaZtrbIZZsRUX/Ew=";
    };
    date = "2025-07-15";
  };
  shoko = {
    pname = "shoko";
    version = "5.1.0-dev.103";
    src = fetchTarball {
      url = "https://github.com/ShokoAnime/ShokoServer/archive/refs/tags/v5.1.0-dev.103.tar.gz";
      sha256 = "sha256-0TWGQTPsGNRxN1SGV4w6HJOs6R7rnDAzwIkFbbUrKYQ=";
    };
  };
  shoko-webui = {
    pname = "shoko-webui";
    version = "2.3.0-dev.4";
    src = fetchTarball {
      url = "https://github.com/ShokoAnime/Shoko-WebUI/archive/refs/tags/v2.3.0-dev.4.tar.gz";
      sha256 = "sha256-ujJ+YKscDwTSckfOQZH0ynSw55fLDPZ0AO9K/KG1zm8=";
    };
  };
  shokofin = {
    pname = "shokofin";
    version = "5.0.3-dev.11";
    src = fetchTarball {
      url = "https://github.com/ShokoAnime/Shokofin/archive/refs/tags/v5.0.3-dev.11.tar.gz";
      sha256 = "sha256-L0AuRNCXs+e2i+c/89TdGvCKgg5eqZJDve2ggqlGStY=";
    };
  };
  suwayomi-server = {
    pname = "suwayomi-server";
    version = "b8e85422f01caf50259ed2ba1e857ccb2f7f65df";
    src = fetchgit {
      url = "https://github.com/Suwayomi/Suwayomi-Server.git";
      rev = "b8e85422f01caf50259ed2ba1e857ccb2f7f65df";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-flWZV/lEXKITJ7KzpNtvykLWHkUuIFwsYNUzkjBdRtQ=";
    };
    date = "2025-07-15";
  };
  suwayomi-webui = {
    pname = "suwayomi-webui";
    version = "4d573174c6df37f3a6b4b16821fc06289fdb4dc9";
    src = fetchgit {
      url = "https://github.com/Suwayomi/Suwayomi-WebUI.git";
      rev = "4d573174c6df37f3a6b4b16821fc06289fdb4dc9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Yv+Y5jJ4AEGt2cW9aSiaOX7oWMR5cqSJq/F2Gc9kU4E=";
    };
    date = "2025-07-15";
  };
  whisparr = {
    pname = "whisparr";
    version = "3.0.0.1163";
    src = fetchurl {
      url = "https://whisparr.servarr.com/v1/update/eros/updatefile?version=3.0.0.1163&os=linux&runtime=netcore&arch=x64";
      name = "whisparr-src-3.0.0.1163.tar.gz";
      sha256 = "sha256-WcrqrQIZbs4U9lmtVUIJmrtkfpyusWI5Wcyd4PbUeBA=";
    };
  };
}
