# SPDX-FileCopyrightText: 2025 Hana Kretzer <hanakretzer@gmail.com>
#
# SPDX-License-Identifier: MIT
when:
  - event: push
    path:
      include:
        - 'flake.lock'
        - '**/*.nix'
  - event: cron
    cron: 'update'

labels:
  backend: local

steps:
  - name: check
    image: bash
    environment:
      NIX_DEBUG: 1
    commands:
      - nix flake check
