# SPDX-FileCopyrightText: 2025 Hana Kretzer <hanakretzer@gmail.com>
#
# SPDX-License-Identifier: MIT
when:
  - event: cron
    cron: 'update'

labels:
  backend: docker

steps:
  - name: update
    image: nixos/nix:latest
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      GITHUB_KEY:
        from_secret: github_ssh_key

      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      NIX_CONFIG: |
        sandbox = true
        extra-experimental-features = nix-command flakes
      USE_BWRAP: 0
      NIX_DEBUG: 1
    privileged: true
    commands:
      - mkdir ~/.ssh ~/.secrets
      - echo "$GITHUB_KEY" > ~/.ssh/id_ed25519
      - |
        echo \
        "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
        git.theless.one ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPkogFEPPOMfkRsBgyuHDQeWQMetWCZbkTpnfajTbu7t" > \
        ~/.ssh/known_hosts
      - |
        echo "[keys]
        github = \"$GITHUB_TOKEN\"" > ~/.secrets/keys.toml
      - echo "$GITHUB_TOKEN" > ~/.secrets/githubToken
      - echo "access-tokens = github.com=$GITHUB_TOKEN" >> /etc/nix/nix.conf
      - chmod 400 ~/.ssh/id_ed25519
      - git config user.email "hanakretzer+autoupdate@gmail.com"
      - git config user.name "nanoyaki (autoupdate)"
      - git config core.sshCommand "ssh -i ~/.ssh/id_ed25519"
      - git remote set-url origin git@github.com:nanoyaki/nanopkgs.git
      - git remote set-url --add origin git@git.theless.one:nanoyaki/nanopkgs.git

      - nix run .#update -- ~/.secrets/keys.toml
      - nix run .#update-readme
      - git add README.md
      - git commit --amend --no-edit

      - (git diff --quiet HEAD $CI_COMMIT_SHA && exit 0) || echo "Updates found, pushing
        commit."
      - git pull --rebase origin main
      - git push --set-upstream origin main
